excluded:
  - Pods
  - DerivedData
  - .build
  - fastlane
  - vendor

disabled_rules:
  - trailing_whitespace # Sometimes formatting with newlines can cause trailing whitespace
  - line_length # We'll use a warning instead of an error for this

opt_in_rules:
  - empty_count # Prefer isEmpty over count == 0
  - empty_string # Prefer isEmpty over string == ""
  - force_unwrapping # Avoid force unwrapping when possible
  - implicitly_unwrapped_optional # Avoid implicitly unwrapped optionals when possible
  - missing_docs # Require documentation for public declarations
  - private_outlet # IBOutlets should be private
  - sorted_imports # Imports should be sorted
  - unneeded_parentheses_in_closure_argument # Avoid unneeded parentheses
  - vertical_parameter_alignment_on_call # Parameters should be aligned vertically

analyzer_rules:
  - unused_declaration
  - unused_import

# Customize rules
line_length:
  warning: 120
  error: 150
  
identifier_name:
  min_length: 2
  excluded:
    - id
    - to
    - in
    - at
    - of
    - up
    - on
    - vm
    - vc

cyclomatic_complexity:
  warning: 15
  error: 25

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 300
  error: 500
  
nesting:
  type_level: 3
  
reporter: "xcode" # Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging) 