name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: |
        swiftlint

    - name: Build
      run: |
        xcodebuild clean build -project SayItDone.xcodeproj -scheme SayItDone -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    - name: Run Tests
      run: |
        xcodebuild test -project SayItDone.xcodeproj -scheme SayItDone -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 